### PR TITLE
Lvpyt 16 store clips on amazon

### PR DESCRIPTION
**Pull request by suchOK**

### CODE REVIEW

**Comment by vova-kul** [comment]
Can one of the admins verify this patch?

**Comment by suchOK** [comment]
Also we have some secret settings for our Amazon S3 bucket. I'll share it later, probably, via Skype.

**Comment by vova-kul** [comment]
Ok to test

**Comment by vova-kul** [comment]
Add boto to requirements.txt

**Comment by ypyrko** [comment]
Approved

**Pull request merged**
